apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py3ocp7ai-svc-development
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/py3ocp7ai-svc/overlays/development
    repoURL: https://github.com/org4rong/py3ocp7ai-src-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-development
    server: https://kubernetes.default.svc
  ignoreDifferences:
    # Ignore PVCs auto-created by StatefulSets
    - group: ""
      kind: PersistentVolumeClaim
      name: minio-data-rag-minio-0
      jsonPointers:
        - /status
        - /metadata/labels
        - /metadata/annotations
    - group: ""
      kind: PersistentVolumeClaim
      name: rag-pgvector-data-rag-pgvector-0
      jsonPointers:
        - /status
        - /metadata/labels
        - /metadata/annotations
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
